Check $avrdude_bin is executable

diff --git a/tools/test-avrdude b/tools/test-avrdude
--- a/tools/test-avrdude
+++ b/tools/test-avrdude
@@ -144,6 +144,7 @@ if [[ ${#pgm_and_target[@]} -eq 0 ]]; then
 fi
 
 arraylength=${#pgm_and_target[@]}
+type "$avrdude_bin" >/dev/null 2>&1 || { echo "$progname: cannot execute $avrdude_bin"; exit 1; }
 echo -n "Testing $avrdude_bin"
 $avrdude_bin -v 2>&1 | grep Version | cut -f2- -d: | sed s/Version/version/
 
