test-avrdude: Abort if running "avrdude -v" fails

diff --git a/tools/test-avrdude b/tools/test-avrdude
--- a/tools/test-avrdude
+++ b/tools/test-avrdude
@@ -149,8 +149,6 @@ fi
 
 arraylength=${#pgm_and_target[@]}
 type "$avrdude_bin" >/dev/null 2>&1 || { echo "$progname: cannot execute $avrdude_bin"; exit 1; }
-echo -n "Testing $avrdude_bin "
-$avrdude_bin -v 2>&1 | grep '[vV]ersion' | sed 's/^.* [Vv]ersion/version/' | head -n1
 
 [[ -d $tmp && -w $tmp ]] || tmp=/tmp # Fall back to /tmp if tmp directory unusable
 status=$(mktemp "$tmp/$progname.status.XXXXXX")
@@ -159,6 +157,17 @@ outfile=$(mktemp "$tmp/$progname.out.XXXXXX")
 tmpfile=$(mktemp "$tmp/$progname.tmp.XXXXXX")
 resfile=$(mktemp "$tmp/$progname.res.XXXXXX")
 trap "rm -f $status $logfile $outfile $tmpfile $resfile" EXIT
+
+echo -n "Testing $avrdude_bin version..."
+$avrdude_bin -v 2>&1 | grep '[vV]ersion' | sed 's/^.* [Vv]ersion //' | head -n1 > "$outfile"
+if test -s "$outfile"; then
+    echo -n " "
+    cat "$outfile"
+else
+    echo " error"
+    $avrdude_bin -v
+    exit 1
+fi
 
 devnull=$tmpfile                # Cannot use /dev/null as file in Windows avrdude
 
